title: ReMemora
email: hello@getrememora.com
description: >- 
  ReMemora is your AI-powered memory for code. Discover, reuse, and remix valuable components across projects.
baseurl: "" 
url: "https://getrememora.github.io"
theme: minima

# 👇 These allow static assets (like your PDF) to be served
include:
  - assets/pdfs

markdown: kramdown
